### PR TITLE
Created Module component and displays titles from Firebase

### PR DESCRIPTION
**Pull request by erinkwon01**
1. Created Module component (Module.jsx) and use propTypes to feed the component the title, styling the div (surrounding the title) with a border
2. Pull modules data from Firebase and map each module to a Module component

Here is what it looks like currently:
image

1. *Currently, we styled the div wrapping the h1 tag (title) with the border. Did you want us to style the h1 tag instead (aka not the div, the h1!)?

### CODE REVIEW

**Review by xu-jerry — APPROVED** [review]
Looks good!

**Comment by xu-jerry** [comment]
Re: your question, having styling on the div is good!! I think for the future though, I would advise against using h1 and other tags like that, but rather defining your own css classes for titles so that it won't apply to every single h1 tag in other files. Like having <div className={styles.h1}> would prob be better long term!

**Comment by erinkwon01** [comment]
I think your part after "Like having" and before "would prob be better ..." got cut off :o but sounds good! I think I just used h1 for now and once we start styling it, I'll add specific classes and use divs :)

**Comment by xu-jerry** [comment]
LOLOL i didn't know github removed all html tags but i meant to say `<div className=styles.title />`

**Pull request merged**
